name: MultipleInventories
version: 1.0
main: fr.zcraft.MultipleInventories.MultipleInventories

description: Multiple inventories actually working
author: Amaury Carrade

commands:
    mi:
        description: Multiple inventories main command
